[package]
name = "res-regex"
version = "0.1.0"
authors = ["rfm <r@robertmasen.pizza>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ress = "0"
log = "0"

[dev-dependencies]
pretty_env_logger = "0"